==================DEFINIÇÃO DE VARIAVEIS =================

SINTAX DE DECLARE -

DECLARE NOMEIDENTIFICADOR[CONSTANT] TIPO_DE_DADO [NOT NULL][:= | DEFAULT expressão;]

SET SERVEROUTPUT ON;

DECLARE 
   VNUMERO NUMBER(11,2) := 110.50;
BEGIN
    DBMS_OUTPUT.PUT_LINE ('Seu numero é = ' || VNUMERO);
END;


==== DECLARANDO VARIAVEIS TIPO CHAR E VARCHAR2 =============

DECLARE 
 VCARACTEREFIXO CHAR (2) := 'R$';
 VCARACTERETAMVARIAVEL VARCHAR2(100) := 'Belo Horizonte, MG';
BEGIN 
  DBMS_OUTPUT.PUT_LINE('String de caracteres de tamanho fixo : ' || VCARACTEREFIXO );
  DBMS_OUTPUT.PUT_LINE ('String de caracteres de tamanh variavel : ' || VCARACTERETAMVARIAVEL);
END;

========== DECLARANDO VARIAVEIS TIPO DATA ============

o formato default de datas no banco de dados é DD/MM/YY - por isso que se você declara variaveis do tipo date irá aparecer como esta configurado na base
caso queira fazer conversão utilize o TOCHAR
DECLARE 
   VDATA1 DATE := '16/11/23';
   VDATA2 DATE := '16/11/2023';
BEGIN 
  DBMS_OUTPUT.PUT_LINE ('DATA 1  = ' || VDATA1);
  DBMS_OUTPUT.PUT_LINE ('DATA 2  = ' || VDATA2 );
END;

============ DECLARANDO CONSTANTES ===========

DECLARE 
  VPI CONSTANT NUMBER (38,15) := 3.1415926;
BEGIN 
  DBMS_OUTPUT.PUT_LINE ('PI = ' || VPI);
END;

Constantes não podem ser alteradas em meio ao seu BEGIN 

EXEMPLO DE ERRO : 

DECLARE 
  VPI CONSTANT NUMBER (38,15) := 3.1415926;
BEGIN 
  DBMS_OUTPUT.PUT_LINE ('PI = ' || VPI);
  VPI := 3.14;
  DBMS_OUTPUT.PUT_LINE ('PI = ' || VPI);
END;

=== COMO FUNCIONAR ALTERANDO VARIAVEIS ====

DECLARE 
  VPI  NUMBER (38,15) := 3.1415926;
BEGIN 
  DBMS_OUTPUT.PUT_LINE ('PI = ' || VPI);
  VPI := 3.14;
  DBMS_OUTPUT.PUT_LINE ('PI = ' || VPI);
END;


========= DECLARE COM P%TYPE ====================

%TYPE - É UM TIPO DE COMANDO QUE COPIA OS TIPO DE DADOS UTILIZADOS DE UMA COLUNA OU TABELA

DECLARE 
 VFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE - AQUI ELE IRÁ ATRIBUIR OS MESMOS TIPOS DE DADOS PARA A VARIAVEL VFIRST_NAME E ASSIM A MESMA IRÁ SER DO MESMO TIPO E DO MESMO TAMANHO
 VLAST_NAME EMPLOYEES.LAST_NAME%TYPE - MESMO CASO 
 
 EXEMPLO
 
 DESC EMPLOYEES;
 
 DECLARE 
 VNUMERO            NUMBER(11,2) := 1200.50;
 VCARACTERTAMFIXO   CHAR(100) := 'Texto de tamanho fixo de até 32767';
 VCARACTERTAMVAR    VARCHAR2(100) := 'Texto de tamanho variavel de até 32767';
 VBOOLEANO          BOOLEAN := TRUE;
 VDATA              DATE := SYSDATE;
 VLONG              LONG := 'Texto tamanho varivael de até 32660';
 VROWID             ROWID;
 VTIMESTAMP         TIMESTAMP := SYSTIMESTAMP;
 VTIMESTAMPTZ       TIMESTAMP WITH TIME ZONE := SYSTIMESTAMP; 
 VCARACTERTAMFIXOUNIVERSAL NCHAR(100) := 'Texto tamanho fixo universal de até 32767';
 VCARACTERTAMVARUNIVERSAL  NVARCHAR2(100) := 'Texto tamanho VARIAVEL universal de até 32767';
 VNUMERO_INTEIRO     BINARY_INTEGER := 1200;
 VNUMERO_FLOAT       BINARY_FLOAT := 150000000;
 VNUMERO_DOUBLE      BINARY_DOUBLE := 1500000000;
 BEGIN 
 DBMS_OUTPUT.PUT_LINE ('NUMERO = ' || VNUMERO);
 DBMS_OUTPUT.PUT_LINE ('String de caracter tam fixo = ' ||  VCARACTERTAMFIXO);
 DBMS_OUTPUT.PUT_LINE ('String de caracter tam VARIAVEL = ' ||  VCARACTERTAMVAR);
 IF VBOOLEANO = TRUE
 THEN 
 DBMS_OUTPUT.PUT_LINE ('Booleano = ' || 'TRUE');
 ELSE 
 DBMS_OUTPUT.PUT_LINE ('Booleano = ' || 'FALSE OR NULL');
 END IF;
 DBMS_OUTPUT.PUT_LINE ('DATA = ' || VDATA);
 DBMS_OUTPUT.PUT_LINE ('LONG = ' || VLONG);
 SELECT ROWID
 INTO VROWID
 FROM EMPLOYEES
 WHERE FIRST_NAME = 'Steven' AND LAST_NAME = 'King';
 DBMS_OUTPUT.PUT_LINE ('ROWID =  ' || VROWID);
 DBMS_OUTPUT.PUT_LINE ('TIMESTAMP = ' || VTIMESTAMP);
 DBMS_OUTPUT.PUT_LINE ('TIMESTAMPTZ = ' || VTIMESTAMPTZ);
 DBMS_OUTPUT.PUT_LINE ('VCARACTERTAMFIXOUNIVERSAL = ' || VCARACTERTAMFIXOUNIVERSAL);
 DBMS_OUTPUT.PUT_LINE ('VCARACTERTAMVARUNIVERSAL = ' || VCARACTERTAMVARUNIVERSAL);
 DBMS_OUTPUT.PUT_LINE ('VNUMERO_INTEIRO = ' || VNUMERO_INTEIRO); 
 DBMS_OUTPUT.PUT_LINE ('VNUMERO_FLOAT = ' || VNUMERO_FLOAT);
 DBMS_OUTPUT.PUT_LINE ('VNUMERO_DOUBLE = ' || VNUMERO_DOUBLE);
 END;
 