FUNÇÕES DO TIPO DATE 

O FORMAT DEFAULT DE EXIBIÇÃO DE DATAS É DEFINIDO PELO DBA ATRAVÉS DO PARAMETRO NLS_DATE_FORMAT 

SELECT SYSDATE
  FROM DUAL;
  
  
---CALCULO DE SYSDATE ---

SELECT SYSDATE , SYSDATE + 3824,SYSDATE - 2
  FROM DUAL
  
SELECT EMP.LAST_NAME, ROUND((SYSDATE -EMP.HIRE_DATE)/7,2) "SEMANAS DE TRABALHO"
  FROM EMPLOYEES EMP
  
====== MESES TRABALHADOS CALCULANDO UTILIZANDO MONTH_BETWEEN =======================
SELECT emp.first_name,emp.last_name,ROUND(MONTH_BETWEEN(SYSDATE,EMP.HIRE_DATE),2) 'MESES DE TRABALHO'
  from employees;
 
 ====== FUNCIONALIDADES DE SYSDATE =====================
 
 
 ADD_MONTH ADICIONA UM MÊS  - COLUNA + A QUANTIDADE
 NEXT_DAY - O PROXIMO DIA DA COLUNA, PODENDO PROCURAR DIAS ESCRITOS
 LAST_DAY - DA COLUNA ESPECIFICADA
  
  SELECT SYSDATE,ADD_MONTHS (SYSDATE,2),NEXT_DAY(SYSDATE,'SEXTA_FEIRA'),LAST_DAY(SYSDATE)
    FROM DUAL;
    
    
ROUND E TRUNC TAMBEM PODE SER UTILIZADO PARA PARAMETROS DE DATAS

ROUND VAI ARREDODNDAR 
E TRUNC IRA RETIRAR MINUTOS SEGUNDOS E HORAS PARA SOMENTE A DATA

SELECT SYSDATE,ROUND(SYSDATE,'MONTH'),ROUND(SYSDATE,'YEAR'),
       TRUNC(SYSDATE,'MONTH'),TRUNC(SYSDATE,'YEAR') 
  FROM DUAL;
  
  
SELECT SYSDATE,TO_CHAR(TRUNC(SYSDATE),'DD/MM/YYYY HH24:MI:SS')
  FROM DUAL;