EXPRESSÕES CONDICIONAIS

   CASE - DECODE
   
====================

BASICAMENTE UM IF-THEN-ELSE DENTRO DE SQL

======= UTILIZANDO CASE ========

CASE WHEN THEN END

SUA SINTAX FUNCIONA DA SEGUINTE MANEIRA, ELE VAI VERIFICAR AS CONDIÇÕES INFORMADAS SE BATEREM ELE INFORMA UMA SITUAÇÃO SE NÃO OUTRA

SELECT EMP.LAST_NAME,
       EMP.JOB_ID,
       EMP.SALARY,
       CASE EMP.JOB_ID
       WHEN 'IT_PROG' THEN 1.10 * SALARY
       WHEN 'ST_CLERK' THEN 1.15 * SALARY
       WHEN 'SA_REP' THEN 1.20 * SALARY
       ELSE SALARY 
       END NOVO_SALARIO
  FROM EMPLOYEES EMP
  

===== FUNÇÃO DECODE =======

DECODE FUNCIONA QUASE A IGUAL A CASE WHEN POREM ELA RESOLVE POR POSIÇÃO,OU SEJA, INDICANDO OS VALORES ELA RESOLVE OS PRIMEIROS DEPOIS O PROXIMO
INDICANDO NO FINAL UM VALORE OU COLUNA DEFAULT CASO SEUS PARAMETROS NÃO BATAM

SELECT EMP.LAST_NAME,
       EMP.JOB_ID,
       EMP.SALARY,
       DECODE(JOB_ID,'IT_PROG'  , 1.10 * EMP.SALARY,
                      'ST_CLERK', 1.15 * EMP.SALARY,
                      'SA_REP'  , 1.20 * EMP.SALARY,
                                         EMP.SALARY) "NOVO SALARIO"
  FROM EMPLOYEES EMP