CONVERSÕES EXPLICITAS E EXPRESSÕES CONDICIONAIS

-------------------------------------------------------

CONVERSÕES EXPLICITAS DE SÃO AS SEGUINTES 

======== PARA NUMEROS =====
TO_CHAR PARA NUMEROS E O MESMO IRÁ TRANSFORMAR ELES EM CARACTERES

TO_NUMBER PARA CARACTERES PARA NUMEROS 

========= PARA DATAS ===========

TO_CHAR PARA DATE PARA TRANSFORMAR EM CARACTERES

TO_DATE DE CARACTERES PARA DATA


TO_CHAR,TO_DATE,TO_NUMBER É UMA FUNÇÃO ONDE A SUA CONVERSÃO EXPLICITA 

SINTAX DE TO_CHAR -

SELECT TO_CHAR( COLUNA TIPO DATE,'FORMATO - DD/MM/YY')
 
- Deve ser definido entre aspas SIMPLES, É case sensitivo e seu formato de data pode ser qualquer um

- FM NO COMEÇO SUPRIME ESPAÇOS EM BRANCO DESNECESSARIOS E ZEROS A ESQUERDA

======== EXEMPLOS COM DATAS ==========
SELECT TO_CHAR(SYSDATE,' DD/MM/YYYY HH24:MI:SS')
  FROM DUAL;
  
SELECT EMP.last_name,TO_CHAR(emp.hire_date,'dd/mm/yyyy hh24:mi:ss') DT_ADMISSÃO
  FROM EMPLOYEES EMP;              --- COMO NÃO HÁ DADOS DE HORAS NA ADIMISSÃO IRA TRAZER VALORES ZERADOS 
  
SELECT EMP.last_name,TO_CHAR(emp.hire_date,'DD "de" Month "de" YYYY hh24:mi:ss') DT_ADMISSÃO
  FROM EMPLOYEES EMP
  
SELECT EMP.last_name,TO_CHAR(emp.hire_date,' FM Day "de" Month "de" YYYY (DD/mm/YYYY) hh24:mi:ss') DT_ADMISSÃO
  FROM EMPLOYEES EMP

  
=========== FUNÇÃO TO CHAR COM NUMEROS ============

9 - APRESENTA OS NUMEROS QUE VOCÊ QUER SUPRIMINDO OS ZEROS A ESQUERDA

0 - IRA TRAZER OS ZEROS A ESQUERDA SOMENTE QUANDO FOR DEFINIDO

$ - MOEDA

L - MOEDA DEFINIDA PELOS PARAMETROS DE NLS_CURRENCY

D OU . PARA DECIMAL

G OU , PARA MILHARES

SELECT EMP.first_name,EMP.last_name, TO_CHAR(salary,'L99G999D99') SALARIO -- DICA AQUI VOCÊ PERCEBEU O SEGUINTE A SINTAX DE DINHEIRO não importa a quantidade importa como é feito
  FROM EMPLOYEES EMP;   -- dinheiro é 000,00 então se for mais, adicione mais um G
  
SELECT EMP.first_name,EMP.last_name, salary
  FROM EMPLOYEES EMP;
  
====== TO_NUMBER CONVERTENDO STRINGS =======

SELECT TO_NUMBER('1200,34') -- CARACTERES ESPECIAIS NÃO CONSEGUIRIA CONVERTER
  FROM DUAL;
  
====== TO_DATE PARA CARACTERES ======

SELECT TO_DATE('06/02/2020','DD/MM/YYYY')
  FROM DUAL;
  
SELECT EMP.FIRST_NAME,EMP.LAST_NAME,EMP.HIRE_DATE
  FROM EMPLOYEES EMP
 WHERE HIRE_DATE = TO_DATE ('17/06/2003','DD/MM/YYYY')
 
 ========== FUNÇÃO ANINHADA ===========
 
SELECT EMP.FIRST_NAME,EMP.LAST_NAME,ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE),0) NUMERO_MESES
  FROM EMPLOYEES EMP
 WHERE HIRE_DATE = TO_DATE('17/06/2003','DD/MM/YYYY');
 