
 ======== GERANCIANDO CONSTRAINTS =============

 ==CONSULTANDO CONSTRAINTS PELO DICIONARIO DE DADOS 
 
 DESC USER_CONSTRAINTS;
 
 DESC USER_CONS_COLUMNS;
 
 
 SELECT CO.CONSTRAINT_NAME,
        CO.CONSTRAINT_TYPE, -- C = CHECK,R = FOREIGN KEY, U = UNIQUE, P = PRIMARY KEY
        CO.SEARCH_CONDITION, 
        CO.R_CONSTRAINT_NAME,
        CO.DELETE_RULE,
        CC.COLUMN_NAME,
        CC.POSITION,
        CO.STATUS
   FROM USER_CONSTRAINTS CO
   JOIN USER_CONS_COLUMNS CC ON (CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
                                 AND CC.TABLE_NAME = CO.TABLE_NAME)
  WHERE CO.TABLE_NAME = 'PROJECTS'
  ORDER BY CO.CONSTRAINT_NAME,CC.POSITION;
  
==== REMOVENDO UMA CONTRAINT A UMA TABELA ====

AQUI FOI REMOVIDO A VALIDAÇÃO DE DEPARTAMENTO DE PROJETOS

ALTER TABLE PROJECTS 
DROP CONSTRAINT PROJECTS_DEPARTMENT_ID_FK;

--- REMOVENDO PK ----- CASCADE É O COMANDO QUE SER UTILIZADO ----

ALTER TABLE PROJECTS 
DROP CONSTRAINT PROJECTS_PROJECT_ID_PK CASCADE;

=== ADICIONANDO UMA CONTRAINT A UMA TABELA 

--adicionando foreign keys ---

ALTER TABLE PROJECTS 
ADD CONSTRAINT PROJECTS_DEPARTMENT_ID_FK
 FOREIGN KEY (DEPARTMENT_ID) 
 REFERENCES DEPARTMENTS (DEPARTMENT_ID)
 
 -- adicionando PRIMARY KEYS ---
 
 ALTER TABLE PROJECTS 
 ADD CONSTRAINT PROJECTS_PROJECT_ID_PK PRIMARY KEY (PROJECT_ID);
 
 ==== DESABILITANDO E HABILITANDO UMA CONSTRAINT ===
 
 DISABLE - DESATIVA O QUE É NECESSARIO POR UM CERTO TEMPO, CASO QUEIRA DESATIVAR UMA PK COM REFERENCIAS É NECESSARIO INFORMAR CASCADE
 ENABLE - ATIVA NOVAMENTE CONSTRAINTS 
 
 ---- DESATIVANDO ----
 
 ALTER TABLE PROJECTS 
 DISABLE CONSTRAINT PROJECTS_DEPARTMENT_ID_FK;
 
 ALTER TABLE PROJECTS 
 DISABLE CONSTRAINT PROJECTS_PROJECT_ID_PK CASCADE
 
 ----- ATIVANDO ------
 
 ALTER TABLE PROJECTS
 ENABLE CONSTRAINT PROJECTS_DEPARTMENT_ID_FK;
 
 
 ALTER TABLE PROJECTS 
 ENABLE CONSTRAINT PROJECTS_PROJECT_ID_PK;
 