=========== SUBCONSULTA MULTIPLE-ROW ===========

SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME
  FROM EMPLOYEES E
 WHERE E.Salary in (SELECT AVG (NVL(E2.SALARY,0))
                      FROM EMPLOYEES E2
                     GROUP BY E2.DEPARTMENT_ID);

============ SUBCONSULT MULTIPLE ROW NOT IN =============

SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME
  FROM EMPLOYEES E
 WHERE E.Salary NOT in (SELECT AVG (NVL(E2.SALARY,0))
                      FROM EMPLOYEES E2
                     GROUP BY E2.DEPARTMENT_ID);
                     
========= UTILIZANDO OPERADOR ANY EM SUB-CONSULTAS MULTIPLE-ROW ===========

VAMOS LA POR QUE ESSE É CONFUSO - 

PONTOS O MESMO É UM OPERADOR QUE BUSCA QUALQUER UM QUE SEJ O MAIOR PARA A SUA CONSULTA NA SUBCONSULTA O MESMO FOI 9000
E SÓ NOS TROUXE OS MENORES A ESTE

E DEVE SER UTILIZADO OS COMPARATIVOS PARA SUA PESQUISA COMO >,<,=<,=>,!=

SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,E.SALARY
  FROM EMPLOYEES E
 WHERE E.Salary != ANY (SELECT E2.SALARY
                      FROM EMPLOYEES E2
                     WHERE JOB_ID = 'IT_PROG');
                     
======= UTILIZANDO OPERADOR ALL EM SUBCONSULTAS MULTIPLE-ROW ========

ESTE TRAZ TODOS EXCETO OS QUE ESTÃO NA CONSULTA OU SEJA ELE PEGOU E FILTROU TUDO PELO VALOR EM ESPECIFICO MENOR

SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,E.SALARY
  FROM EMPLOYEES E
 WHERE E.Salary < ALL (SELECT E2.SALARY
                      FROM EMPLOYEES E2
                     WHERE JOB_ID = 'IT_PROG');
                     
======== CUIDADOS COM VALORES NULOS EM UMA SUBCONSULTA COM OPERADOR IN 

O MESMO PEGA VALORES NULOS TAMBEM ELE SE COMPORTA COMO SE FOSSE UM OR 
JÁ O NOT IN SE COMPORTA COMO O AND

SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,E.MANAGER_ID
  FROM EMPLOYEES E
 WHERE E.EMPLOYEE_ID     IN (SELECT E2.MANAGER_ID
                               FROM EMPLOYEES E2);
