=== COMANDOS DE CURSOR ============
SET SERVEROUTPUT ON;

DECLARE 
      VDEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE := 60;
      VPERCENTUAL NUMBER (3) := 10;
BEGIN
     UPDATE EMPLOYEES
     SET SALARY = SALARY * (1 + VPERCENTUAL /100)
     WHERE DEPARTMENT_ID = VDEPARMENT_ID;
     DBMS_OUTPUT.PUT_LINE ('NUMERO DE EMPREGADOS ATUALIZADOS : ' || SQL%ROWCOUNT);
     --COMMIT;
     END;
     
ROLLBACK;

======= REGRA DE PRECEDENCIAS ===============
DECLARE 
        VNOTA1 NUMBER (11,2) := 7.0;
        VNOTA2 NUMBER (11,2) := 6.0; 
        VNOTA3 NUMBER (11,2) := 9.0;
        VNOTA4 NUMBER (11,2) := 6.0;
        VMEDIA NUMBER (11,2);
BEGIN
     VMEDIA := (VNOTA1 + VNOTA2 + VNOTA3 + VNOTA4)/4;
     DBMS_OUTPUT.PUT_LINE ('MEDIA = ' ||vmedia);
     
END;

============ COMANDO IF ===============
ACCEPT PDEPARTMENT_ID PROMPT 'Digite o ID  do departamento : ' -- ACCEPT É COMANDO DO SQL PLUS E ESTA DEFININDO UMA VARIAVEL - PROMPT - VAI APARECER A TELA PARA DIGITAR

DECLARE 
        VPERCENTUAL NUMBER (3);
        VDEPARMENT_ID EMPLOYEES.EMPLOYEE_ID%TYPE := &PDEPARTMENT_ID;
BEGIN 
     IF VDEPARMENT_ID  = 80
     THEN 
     VPERCENTUAL := 10; -- SALES
     ELSE 
         IF VDEPARMENT_ID  = 20
         THEN 
         VPERCENTUAL := 15; --MARKETING
         ELSE 
            IF
            VDEPARMENT_ID  = 60
            THEN 
                VPERCENTUAL := 20; --IT
            ELSE 
                VPERCENTUAL := 5;
            END IF;
        END IF;
    END IF;
    DBMS_OUTPUT.PUT_LINE ('ID DO DEPARTAMENTO  = ' || VDEPARMENT_ID);
    DBMS_OUTPUT.PUT_LINE ('PERCENTUAL DO SETOR = ' || VPERCENTUAL);
    
    UPDATE EMPLOYEES
    SET SALARY = SALARY * (1+  VPERCENTUAL/100)
    WHERE DEPARTMENT_ID = VDEPARMENT_ID;
    END;