=== COMANDOS DE CURSOR ============
SET SERVEROUTPUT ON;

DECLARE 
      VDEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE := 60;
      VPERCENTUAL NUMBER (3) := 10;
BEGIN
     UPDATE EMPLOYEES
     SET SALARY = SALARY * (1 + VPERCENTUAL /100)
     WHERE DEPARTMENT_ID = VDEPARMENT_ID;
     DBMS_OUTPUT.PUT_LINE ('NUMERO DE EMPREGADOS ATUALIZADOS : ' || SQL%ROWCOUNT);
     --COMMIT;
     END;
     
ROLLBACK;

======= REGRA DE PRECEDENCIAS ===============
DECLARE 
        VNOTA1 NUMBER (11,2) := 7.0;
        VNOTA2 NUMBER (11,2) := 6.0; 
        VNOTA3 NUMBER (11,2) := 9.0;
        VNOTA4 NUMBER (11,2) := 6.0;
        VMEDIA NUMBER (11,2);
BEGIN
     VMEDIA := (VNOTA1 + VNOTA2 + VNOTA3 + VNOTA4)/4;
     DBMS_OUTPUT.PUT_LINE ('MEDIA = ' ||vmedia);
     
END;

============== COMANDO IF =============

ACCEPT PDEPARMENT_ID PROMPT 'Digite o id do departmaneto'
   DECLARE 
   VPERCENTUAL       NUMBER(3);
   VDEPARTMENT_ID   EMPLOYEES.EMPLOYEE_ID%TYPE := &PDEPARMENT_ID;
BEGIN 
    IF VDEPARTMENT_ID = 90
    THEN
        VPERCENTUAL := 10; -- SALES
    ELSIF VDEPARTMENT_ID = 20
    THEN 
         VPERCENTUAL := 15; --MARKETING
    ELSIF VDEPARTMENT_ID =60
    THEN 
        VPERCENTUAL :=20; --IT
    ELSE 
        VPERCENTUAL := 5;
    END IF;
    DBMS_OUTPUT.PUT_LINE ('ID DO DEPARTAMENTO  = ' || VDEPARTMENT_ID);
    DBMS_OUTPUT.PUT_LINE ('PERCENTUAL DO SETOR = ' || VPERCENTUAL);
    
    
    UPDATE EMPLOYEES
    SET SALARY = SALARY * (1 + VPERCENTUAL/100)
    WHERE DEPARTMENT_ID = VDEPARTMENT_ID;
    END;

========= COMANDO CASE ===============

SET SERVEROUTPUT ON;

ACCEPT PDEPARMENT_ID PROMPT 'Digite o id do departmaneto'
   DECLARE 
   VPERCENTUAL       NUMBER(3);
   VDEPARTMENT_ID   EMPLOYEES.EMPLOYEE_ID%TYPE := &PDEPARMENT_ID;
BEGIN
    CASE VDEPARTMENT_ID 
    WHEN 60
    THEN 
        VPERCENTUAL := 10; -- SALES
    WHEN 20
    THEN
        VPERCENTUAL := 15; --MARKETING
    WHEN 60
    THEN 
        VPERCENTUAL := 20; --IT
    ELSE
        VPERCENTUAL :=5; 
    END CASE;
    
    DBMS_OUTPUT.PUT_LINE ('ID DO DEPARTAMENTO  = ' || VDEPARTMENT_ID);
    DBMS_OUTPUT.PUT_LINE ('PERCENTUAL DO SETOR = ' || VPERCENTUAL);
    UPDATE EMPLOYEES
    SET SALARY = SALARY * (1 + VPERCENTUAL / 100)
    WHERE DEPARTMENT_ID = VDEPARTMENT_ID;
    END;
    
    
==== OUTRO METODO DE CASE =========

SET SERVEROUTPUT ON;

ACCEPT PDEPARMENT_ID PROMPT 'Digite o id do departmaneto'
   DECLARE 
   VPERCENTUAL       NUMBER(3);
   VDEPARTMENT_ID   EMPLOYEES.EMPLOYEE_ID%TYPE := &PDEPARMENT_ID;
BEGIN
    CASE 
    WHEN VDEPARTMENT_ID = 60 THEN VPERCENTUAL := 10; -- SALES
    WHEN VDEPARTMENT_ID = 20 THEN VPERCENTUAL := 15; --MARKETING
    WHEN VDEPARTMENT_ID = 60 THEN VPERCENTUAL := 20; --IT
    ELSE VPERCENTUAL :=5; 
    END CASE;
    
    DBMS_OUTPUT.PUT_LINE ('ID DO DEPARTAMENTO  = ' || VDEPARTMENT_ID);
    DBMS_OUTPUT.PUT_LINE ('PERCENTUAL DO SETOR = ' || VPERCENTUAL);
    
    UPDATE EMPLOYEES
    SET SALARY = SALARY * (1 + VPERCENTUAL / 100)
    WHERE DEPARTMENT_ID = VDEPARTMENT_ID;
    END;
    