 ============= NESTED TABLE ===================

NESTED TALBE INDICES PODEM SER SOMENTE POSITIVOS
INDEX BY É somente para assossiative arry

* PODE 


DECLARE 
  TYPE NOME_TIPO_TABLE
IS TABLE OF NOME_TABELA.NOME_COLUNA%TYPE;

NOME_VARIAVEL_TABLE NOME_TIPO_TABLE
                    := NOME_TIPO_TABLE(); -- INICIAR 
    --PARA ATRIBUIR VALOR NA VARIAVEL DEVE-SE COLOCAR EXTEND                
BEGIN
     NOME_VARIAVEL_TABLE.EXTEND
     NOME_VARIAVEL_TABLE(INDICE) := VALOR|Expressão;
    
    SET SERVEROUTPUT ON;
    SET VERIFY OFF;

DECLARE 
    TYPE NUMERO_TABLE_TYPE IS TABLE OF INTEGER(2);
    NUMERO_TABLE NUMERO_TABLE_TYPE := NUMERO_TABLE_TYPE();    
BEGIN
  -- ARMAZENA NUMEROS 1 A 10 EM UM ASSOCIATIVE ARRAY
  FOR i IN 1..10
  LOOP
     NUMERO_TABLE.EXTEND;
     NUMERO_TABLE(i) := i;
  END LOOP;
  FOR i IN 1..10
  LOOP
  DBMS_OUTPUT.PUT_LINE ('NESTED TABLE : INDICE = '|| TO_CHAR(i) || ', Valor = '|| TO_CHAR(Numero_table(i)));
  end loop;
end;