================== UITILIZANDO COMANDOS SQL NA LINGUAGEM PL/SQL ===============

Não se pode utilizar comandos DDL - DCL  na lingua do codigo PL/SQL - MAS PODE SE UTILIZAR NO SQL DINAMICO

PL/SQL - DEVE RETORNAR SOMENTE UMA LINHA CASO OCORRA ELE IRA APRESENTAR ERRO DE TOO MANY ROWS

AO CONTRARIO SERA NENHUMA LINHA E TERA NO_DATA_FOUND


Sintaxe 

PL/SQL - 

SELECT COLUNA1,[COLUNA2]
INTO VARIAVEL1[variavel]
FROM TABELA1,[TABELA2]
ETC...


= OBS :
SET SERVEROUTPUT ON;

DECLARE
      VFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
      VLAST_NAME  EMPLOYEES.LAST_NAME%TYPE;
      VSALARY     EMPLOYEES.SALARY%TYPE;
      VEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE := 128;
BEGIN 
     SELECT FIRST_NAME,LAST_NAME,SALARY
     INTO VFIRST_NAME,VLAST_NAME,VSALARY
     FROM EMPLOYEES
     WHERE EMPLOYEE_ID = VEMPLOYEE_ID;
     DBMS_OUTPUT.PUT_LINE ('Employee_id = ' || VEMPLOYEE_ID);
     DBMS_OUTPUT.PUT_LINE ('First_name = ' || VLAST_NAME);
     DBMS_OUTPUT.PUT_LINE ('LAST_NAME = ' || VLAST_NAME);
     DBMS_OUTPUT.PUT_LINE ('Salary = ' || VSALARY);  
END;
--------- EXEMPLO 2 -----------------

DECLARE
      VJOB_ID      EMPLOYEES.JOB_ID%TYPE := 'IT_PROG';
      VAVG_SALARY  EMPLOYEES.SALARY%TYPE;
      VSUM_SALARY  EMPLOYEES.SALARY%TYPE;
BEGIN 
     SELECT ROUND (AVG (SALARY),2),ROUND(SUM(SALARY),2)
     INTO VAVG_SALARY,VSUM_SALARY
     FROM EMPLOYEES
     WHERE JOB_ID = VJOB_ID;
     DBMS_OUTPUT.PUT_LINE ('JOB_ID = ' || VJOB_ID);
     DBMS_OUTPUT.PUT_LINE ('AVG SALARY = ' || VAVG_SALARY);
     DBMS_OUTPUT.PUT_LINE ('SUM SALARY = ' || VSUM_SALARY);
END;

============= INSERTS EM DE DENTRO DE DECLARES ==============


DECLARE
      VFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
      VLAST_NAME  EMPLOYEES.LAST_NAME%TYPE;
      VSALARY     EMPLOYEES.SALARY%TYPE;
BEGIN 
        INSERT INTO EMPLOYEES
        (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID)
        VALUES
        (EMPLOYEES_SEQ.NEXTVAL,'Kobe','Bryant','KBRYANT','515.123.45568',SYSDATE,'IT_PROG',15000,0.4,103,60);
        COMMIT;
    END;
    
========= UPDATES EM PL/SQL ======
    
    DECLARE 
            VEMPLOYEE_ID    EMPLOYEES.EMPLOYEE_ID%TYPE;
            VPERCENTUAL     NUMBER (3) := 10;
        BEGIN 
         UPDATE EMPLOYEES
         SET SALARY = SALARY * (1 + VPERCENTUAL / 100)
         WHERE EMPLOYEE_ID = VEMPLOYEE_ID;
        COMMIT;
    END;
    
    
========= DELETE EM PLSQL ======

DECLARE 
        VEMPLOYEE_ID    EMPLOYEES.EMPLOYEE_ID%TYPE := 207;
    BEGIN 
        DELETE FROM EMPLOYEES
        WHERE EMPLOYEE_ID = VEMPLOYEE_ID;
        COMMIT;
    END;
        
        

