=============== RECORD ================

SINTAX 

DECLARE
TYPE NOME_TIPO_RECORD IS RECORD
(CAMPO[,CAMPOS]);

NOME_VARIAVEL_RECORD NOME_TIPO_RECORD;



TYPE - DEFINE O TIPO QUE VAI SER PASSADO
%TYPE - DEFINE O DADO ATRAVÉS DE OUTRO JÁ EXISTENTE
%ROWTYPE - DEFINE UM RECORD COM BASE EM UMA TABELA

=========== CRIANDO UMA PL/SQL RECORD =========
DECLARE
TYPE EMPLOYEE_RECORD_TYPE IS RECORD  --ESSE É PADRÃO RECOMENDADO PELA ORACLE
  (EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE,
  FIRST_NAME   EMPLOYEES.FIRST_NAME%TYPE,
  LAST_NAME    EMPLOYEES.LAST_NAME%TYPE,
  EMAIL        EMPLOYEES.EMAIL%TYPE,
  PHONE_NUMBER EMPLOYEES.PHONE_NUMBER%TYPE);
  EMPLOYEE_RECORD EMPLOYEE_RECORD_TYPE; --ESTOU INDICANDO QUE A MESMA TEM TODAS AS VARIAVEIS
                                        --A VARIAVEL VAI TER TODAS AS VARIAVEIS DO RECORD TYPE
    
    

SET SERVEROUTPUT ON; 
SET VERIFY OFF;

ACCEPT PEMPLOYEE_ID PROMPT 'Digite o id do empregado : '
DECLARE
TYPE EMPLOYEE_RECORD_TYPE IS RECORD
  (EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE,
  FIRST_NAME   EMPLOYEES.FIRST_NAME%TYPE,
  LAST_NAME    EMPLOYEES.LAST_NAME%TYPE,
  EMAIL        EMPLOYEES.EMAIL%TYPE,
  PHONE_NUMBER EMPLOYEES.PHONE_NUMBER%TYPE);
  EMPLOYEE_RECORD EMPLOYEE_RECORD_TYPE;

BEGIN 
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER
INTO EMPLOYEE_RECORD
FROM EMPLOYEES
WHERE EMPLOYEE_ID = &PEMPLOYEE_ID;
DBMS_OUTPUT.PUT_LINE (EMPLOYEE_RECORD.EMPLOYEE_ID || ' - ' || 
                      EMPLOYEE_RECORD.FIRST_NAME || ' - '  ||
                      EMPLOYEE_RECORD.LAST_NAME || ' - '   ||
                      EMPLOYEE_RECORD.EMAIL || ' - ' ||
                      EMPLOYEE_RECORD.PHONE_NUMBER);
END;                      
    
============ UM OUTRO JEITO DE DEFINIR UMA VARIAVEL RECORD É =========

QUE BASICAMENTE DESIGNA TODAS AS COLUNAS DA TABELA PARA A VARIAVEL RECORD

ACCEPT PEMPLOYEE_ID PROMPT 'Digite o id do funcionario'
DECLARE 
     EMPLOYEE_RECORD EMPLOYEES%ROWTYPE;
     VEMPLOYEE_ID    EMPLOYEES.EMPLOYEE_ID%TYPE := &PEMPLOYEE_ID;
BEGIN 
SELECT *
INTO EMPLOYEE_RECORD
FROM EMPLOYEES
WHERE EMPLOYEE_ID = VEMPLOYEE_ID;
DBMS_OUTPUT.PUT_LINE (EMPLOYEE_RECORD.EMPLOYEE_ID || ' - ' || 
                      EMPLOYEE_RECORD.FIRST_NAME || ' - '  ||
                      EMPLOYEE_RECORD.LAST_NAME || ' - '   ||
                      EMPLOYEE_RECORD.EMAIL || ' - ' ||
                      EMPLOYEE_RECORD.PHONE_NUMBER);
END;