CONTROLANDO TRANSAÇÕES EM PL/SQL

SET SERVEROUTPUT ON;

DECLARE 
  VEMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE := 150;
  BEGIN 
  SAVEPOINT INSERTOK;

INSERT INTO EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID)
     VALUES  (EMPLOYEES_SEQ.NEXTVAL,'Kobe','Bryant','KBRYANT','515.123.45568',SYSDATE,'IT_PROG',15000,0.4,103,60);
    
  UPDATE EMPLYOYEES
  SET SALARY = 1500
  WHERE JOB_ID = 'IT_PROG';

    ROLLBACK INSERTOK;
    COMMIT;
END;
       

  COMMIT;
END;
