CREATE TABLE TABELA_JOGA_FORA (	
CONSTRAINT ID_CARGO PRIMARY KEY 
NOME VARCHAR2(10),
CARGO VARCHAR2(35),
SALARIO NUMBER(6,0),
SETOR NUMBER(6,0)
);

SET SERVEROUTPUT ON;
SELECT * FROM TABELA_JOGA_FORA

ACCEPT PCARGO_ID PROMPT 'Digite o id do CARGO para inserir : '
ACCEPT PNOME PROMPT 'Digite o nome : '

DECLARE 
    
    VCARGO           TABELA_JOGA_FORA.SALARIO_DAVID%TYPE := &PCARGO_ID;
    VNOME            TABELA_JOGA_FORA.NOME_PESSOA%TYPE   := '&PNOME';
    
BEGIN

    CASE VCARGO
    
    WHEN 1 THEN INSERT INTO TABELA_JOGA_FORA VALUES ('T.I','PROGRAMADOR',3000,4000,VNOME);
    WHEN 2 THEN INSERT INTO TABELA_JOGA_FORA VALUES ('CPD','ATENDIMENTO',2000,1000,VNOME);
    WHEN 3 THEN INSERT INTO TABELA_JOGA_FORA VALUES ('BURRO','BURRO',NULL,NULL,VNOME);
    
    END CASE;

    DBMS_OUTPUT.PUT_LINE ('Cadastro realizado na tabela TABELA_JOGA_FORA ' || 'PESSOA : ' || VNOME);    
    DBMS_OUTPUT.PUT_LINE ('Cadastro realizado na tabela TABELA_JOGA_FORA ' || 'ID DO CARGO : ' || VCARGO);

END;
    
    
    SELECT * FROM TABELA_JOGA_FORA 
    
    ALTER TABLE TABELA_JOGA_FORA ADD (NOME_PESSOA VARCHAR2(50));

