=========== VARRAY ===================

O MESMO É LIMITADO É O MENOS USADO;

DECLARE
     TYPE NOME_TIPO_VARRAY IS VARRAY | VARYNG ARRAY (LIMITE) OF NOME_TABLE.NOME_COLUNA%TYPE;
     NOME_VARIAVEL_VARRAY   NOME_TIPO_VARRAY := NOME_TIPO_VARRAY();

BEGIN 
     NOME_VARIAVEL_VARRAY.EXTEND
     NOME_VARIAVEL_VARRAY(INDICE) := VALOR | EXPRESSÃO -- := voce inicializa com o construtor ou seja com a propria variavel criada
     
SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE 
  TYPE NUMERO_TABLE_TYPE IS VARRAY (10) OF INTEGER (2);
  NUMERO_TABLE NUMERO_TABLE_TYPE := NUMERO_TABLE_TYPE();

BEGIN 
  FOR i in 1 .. 10
  LOOP
  NUMERO_TABLE.EXTEND;
  NUMERO_TABLE (i) := i;
END LOOP;  
   for i in 1..10
   LOOP 
  DBMS_OUTPUT.PUT_LINE ('VARRAY : INDICE = '|| TO_CHAR(i) || ', Valor = '|| TO_CHAR(NUMERO_TABLE(i)));
END LOOP;
END;


SET SERVEROUTPUT ON;

DECLARE 
   TYPE DATA_RECORD_TYPE IS VARRAY (50) OF VARCHAR2 (10);
   DATA_RECORD DATA_RECORD_TYPE := DATA_RECORD_TYPE(null,null);

BEGIN
    DATA_RECORD(1) := 'BANANA';
    DATA_RECORD(2) := 'MACACO';
DBMS_OUTPUT.PUT_LINE ('MACACO GOSTA DE : '       ||DATA_RECORD(1));
DBMS_OUTPUT.PUT_LINE  ('BANANA É COMIDA POR : ' || DATA_RECORD(2) );
END;




===== BULK COLLECTION DE VARRAY ====

DECLARE 
  TYPE EMPLOYEES_TABLE_TYPE IS VARRAY (200)  OF EMPLOYEES%ROWTYPE;
  EMPLOYEES_TABLE EMPLOYEES_TABLE_TYPE := EMPLOYEES_TABLE_TYPE();

BEGIN 
  SELECT *
  BULK COLLECT INTO EMPLOYEES_TABLE
  FROM EMPLOYEES;
  FOR i IN EMPLOYEES_TABLE.FIRST .. EMPLOYEES_TABLE.LAST
  LOOP
  DBMS_OUTPUT.PUT_LINE (EMPLOYEES_TABLE(i).employee_id || ' ' || 
                        EMPLOYEES_TABLE(i).first_name);
  end loop;
end;