=== UTILIZANDO OS COMANDOS DE ALTER TABLE =========

-- COMANDO TIPO DDL -

== ADICIONANDO COLUNAS

ALTER TABLE PROJECTS 
ADD (DEPARTMENT_ID NUMBER(3));

ALTER TABLE PROJECTS
  ADD (DEPARTMENT_ID NUMBER(3)DEFAULT (0) NOT NULL );

==  RETIRANDO COLUNAS

ALTER TABLE PROJECTS 
DROP COLUMN DEPARTMENT_ID;

DESC PROJECTS;


== MODIFICANDO COLUNAS 

ALTER TABLE PROJECTS
  MODIFY (PROJECT_CODE VARCHAR2(6));
  

ALTER TABLE PROJECTS
  MODIFY (PROJECT_CODE VARCHAR2(6)NULL);
  
         
         MAIS DE UM

ALTER TABLE PROJECTS
  MODIFY (PROJECT_CODE VARCHAR2(6)NULL,
          STATUS NUMBER(10) NULL );
  
  FORMATO ORIGINAL
  
  ALTER TABLE PROJECTS
  MODIFY (PROJECT_CODE VARCHAR2(10)NOT NULL,
          STATUS VARCHAR2(20) NOT NULL );
  
  
=== RENOMEANDO COLUNAS ==

 ALTER TABLE PROJECTS
RENAME COLUMN PRIORITY TO PRIORIDADE;

=== ALTERANDO A TABELA PARA O STATUS READ ONLY

AQUI CASO A PESSOA TENTE FAZER COMANDOS DDL OU DML IRA OCORRER ERRO POIS ESTA SO PARA LEITURA

ALTER TABLE EMPLOYEES READ ONLY;

=== ALTERANDO A  TABELA PARA O STATUS READ WRITE

VOLTANDO A PERMITIR QUE A TABELA POSSA SER ALTERADA 

ALTER TABLE EMPLOYEES READ WRITE;   