UTILIZANDO GRUPOS PARTE 2 

SUA SEQUENCIA LOGICA 

1 - WHERE - SELECIONA AS LINHAS A SEREM RECUPERADAS 

2 - GROUP BY - FORMAR OS GRUPOS 

3 - HAVING - SELECIONAR OS GRUPOS A SEREM RECUPERADOS 

4 - EXIBIR COLUNAS OU EXPRESSÕES DO SELECT ORDENANDO PELO CRITÉRIO DEFINIDO NO ORDER BY

  
==== CRIANDO GRUPOS UTILIZANDO A CLAUSULA GROUP BY =======

SELECT DEPARTMENT_ID,JOB_ID,SUM(SALARY)
  FROM EMPLOYEES EMP
 GROUP BY DEPARTMENT_ID,JOB_ID
 ORDER BY DEPARTMENT_ID,JOB_ID;
 
 
 
SELECT DEPARTMENT_ID,JOB_ID,AVG(NVL(SALARY,0))
  FROM EMPLOYEES EMP
 GROUP BY DEPARTMENT_ID,JOB_ID
 ORDER BY DEPARTMENT_ID,JOB_ID;
 
 
 ====== UTILIZANDO FUNÇÕES DE GRUPO DE MODO ERRADO =============
 
 
SELECT DEPARTMENT_ID,JOB_ID,SUM(SALARY)
  FROM EMPLOYEES EMP
 GROUP BY DEPARTMENT_ID
 ORDER BY DEPARTMENT_ID;
 
 
 ==== CONSULTA INCORRETA DE FUNÇÕES DE GRUPO  ===
 
SELECT DEPARTMENT_ID,MAX(SALARY)
  FROM EMPLOYEES EMP
 WHERE MAX (SALARY) > 1000
 GROUP BY DEPARTMENT_ID
 ORDER BY DEPARTMENT_ID;
  
Por que isso ocorre pois a clasula where so procura linhas e a função de agrupamento nele não funciona 

======= UTILIZANDO HAVING PARA FUNÇÕES DE AGRUPAMENTO ===========

SELECT DEPARTMENT_ID,MAX(SALARY)
  FROM EMPLOYEES EMP
 GROUP BY DEPARTMENT_ID
 HAVING MAX (SALARY) > 1000
 ORDER BY DEPARTMENT_ID;
 
 
 SELECT JOB_ID,SUM(SALARY) TOTAL
   FROM EMPLOYEES 
  WHERE JOB_ID <> 'SA_REP'
  GROUP BY JOB_ID 
 HAVING SUM (SALARY) > 10000
 ORDER BY JOB_ID;
 
 HAVING SERIA BASICAMENTE UM WHERE DE FUNÇÕES DE GRUPO 
 
 ======== ANINHANDO FUNÇÕES DE GRUPO ==========
 
    FUNÇÕES DE GRUPO SÓ PODEM SER ANINHADAS UMA UNICA VEZ 
 
 SELECT MAX(AVG(SALARY))
   FROM EMPLOYEES
  GROUP BY DEPARTMENT_ID;