FUNÇÕES DE MANIPULAÇÃO DE QUERYS NUMEROS 

ROUND - TRUNC - MOD 
=========== ROUND ============
ROUND - ARREDONDA O NUMERO O VALORA NA CASA DECIMAL ESPECIFICADA

SINTAX COLUNA OU EXPRESSÃO NUMERICA QUE SERA ARREDONDADA ,A QUANTIDADE DE PRECISÃO PARA SEU ARREDONDAMENTO

SELECT ROUND (498.6165156451566,6),ROUND (498.6321,0)
  FROM DUAL;

LEMBRANDO QUE NUMEROS MENORES QUE 1 A 5 ELE CORTA E NUMEROS ACIMA DE 6 A 9 ELE ADICIONA NO TOTAL A FRENTE   
========== TRUNC ============

TRUNC - TRUNCA AS CASAS DECIMAIS O VALOR NA CASA DECIMAL ESPECIFICADA

ELE IRA CORTAR SEM SE PREOCUPAR COM ARREDODANEMNTOS

SELECT TRUNC(111.88,0),TRUNC(1156316.156321,2)
  FROM DUAL
  
=============MOD =============

MOD - RETORNA UM RESTO DE DIVISÃO

SELECT MOD (111,2)
  FROM DUAL
  
  
======== ABS ==========

ABS - RETORNA O NUMERO ABSOLUTO DO NUMERO OU SEJA POSITIVO

SELECT ABS(ROUND(-4894.682,2))
  FROM DUAL
  
=======SQRT =========

SQRT - RAIZ QUADRADA DO NUMERO

SELECT SQRT(20)
  FROM DUAL;