FUNÇÕES GENERICAS 

NVL - NVL2 - NULLIF - COALESCE 

======= FUNÇÃO NVL ======

CONVERTE VALORES NULOS EM OUTRO VALOR DEFINIDO

TIPOS DE DADOS UTILIZADOS  -DATE - CHAR/VARCHAR - NUMBER

EXEMPLO :

SELECT EMP.LAST_NAME,
       EMP.SALARY,
       NVL(EMP.COMMISSION_PCT,0),SALARY*12 SALARIO_ANUAL,
      (SALARY*12) + (SALARY*12*NVL(EMP.COMMISSION_PCT,0))REMUNERACAO_ANUAL
  FROM EMPLOYEES EMP
  
  
=== UTILIZANDO A FUNÇÃO COALESCE =======

FUNÇÃO COALESCE PODE RECEBER MULTIPLOS ARGUNTEMNTOS, SE A PRIMEIRA EXPRESSÃO RETORNA NULL A FUNÇÃO COALESCE RETORNA ESTA EXPRESSÃO;
SENÃO A FUNÇÃO SEGUIRÁ AVALIADO AS EXPRESSÕES SEGUINTES

SELECT COALESCE (NULL,NULL,'BANANA'),COALESCE(NULL,'CHIBATA','BANANA'),
       COALESCE ('CANECA','SAMBA','TELEFONE')
  FROM DUAL;


SELECT EMP.LAST_NAME,EMP.EMPLOYEE_ID,EMP.MANAGER_ID,EMP.COMMISSION_PCT,COALESCE (TO_CHAR(EMP.COMMISSION_PCT),TO_CHAR(MANAGER_ID),
       'SEM PERCENTUAL DE COMISSÃO E SEM GERENTE')
  FROM EMPLOYEES EMP;
  
======== UTILIZANDO FUNÇÃO NVL2 ========

NVL2 É A MESMA COISA DO NVL NORMAL, POREM ACEITA MAIS ARGUMENTOS E MAIS PARAMETROS
NVL2 FUNCIONA ASSIM  - ARGUMENTO, IFNOTNULL, IFNULL 

SELECT EMP.LAST_NAME,EMP.SALARY,EMP.COMMISSION_PCT,
       NVL2(EMP.COMMISSION_PCT,10,0)
  FROM EMPLOYEES EMP;


==== UTILIZANDO NULLIF ======

NULIFICA VALORES QUE FOREM IGUAIS EM SEU PARAMETROS COMPARA O PRIMEIRO COM O SEGUNDO

SELECT NULLIF(1000,1000),NULLIF(1000,2000)
 FROM DUAL;

  
SELECT EMP.FIRST_NAME,EMP.LAST_NAME,length (EMP.FIRST_NAME) expressao_1,
      length (emp.last_name) expressao_2,NULLIF (LENGTH(emp.first_name),length(emp.last_name)) RESULTADO
  FROM EMPLOYEES EMP
  

